redis:
    privileged: true
    build: ./redis/
    ports:
        - "127.0.0.1:6379:6379"        
mysql:
    privileged: true
    build: ./mysql/
    ports:
        - "127.0.0.1:3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "123456"    
php:
    privileged: true
    build: ./php/
    ports:
        - "9000:9000"
    volumes:
        - ./www:/usr/share/nginx/html
        - ./php/php-fpm:/usr/local/php/etc/php-fpm.d
        - ./php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
    links:
        - redis
        - mysql
nginx:
    privileged: true
    build: ./nginx/
    ports:
        - "80:80"
        #- "81:81"
        - "8000:8000"
       # - "82:82"
       # - "83:83"
    volumes:
        - ./www:/usr/share/nginx/html
        - ./www/logs:/var/log/nginx
        - ./nginx/site:/etc/nginx/conf.d
        - ./nginx/conf:/etc/nginx/conf
    links:
        - php    
