php:
    build: ./php/
    ports:
        - "9000:9000"
    volumes:
        - ./www:/usr/share/nginx/html
        - ./php/php-fpm:/usr/local/php/etc/php-fpm.d
        - ./php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
nginx:
    build: ./nginx/
    ports:
        - "80:80"
        - "81:81"
        - "8000:8000"
    volumes:
        - ./www:/usr/share/nginx/html
        - ./www/logs:/var/log/nginx
        - ./nginx/site:/etc/nginx/conf.d
    links:
        - php    
        
