php:
    build: ./php/
    ports:
        - "9000:9000"
    volumes:
        - ./www:/usr/share/nginx/html
        - ./php/php-fpm:/etc/php-fpm.d
nginx:
    build: ./nginx/
    ports:
        - "80:80"
        - "81:81"
    volumes:
        - ./www:/usr/share/nginx/html
        - ./www/logs:/var/log/nginx
        - ./nginx/site:/etc/nginx/conf.d
    links:
        - php    
        
